### ISSUE TITLE
IMPORTANT: what's left to do

### ISSUE THREAD

**Issue by ghost** [Aaaaaaa3/musicSchooooooooooooooooooooool#18]
1) print out to file
2) sorting - needs to be implemented 
3) logic for teachers
4) GUI
5) alerts

**Comment by ghost** [comment]
1) print out to file
    2) sorting - needs to be implemented
    3) logic for teachers
  4)   GUI
   5)  alerts - needs to be implemented

**Comment by ghost** [comment]
1. print out to file
    2. sorting - needs to be implemented
    3. logic for teachers
    4. GUI
    5. alerts - needs to be implemented
6. comments + headers

**Comment by Aaaaaaa3** [comment]
if worst comes to worst we can just say list contains everything
so we don't differentiate between instruments vs sheet music
