### ISSUE TITLE
user methods

### ISSUE THREAD

**Issue by Aaaaaaa3** [Aaaaaaa3/musicSchooooooooooooooooooooool#5]
Student
- check if student when signing out

Teacher
- sort chronologically

**Comment by ghost** [comment]
public boolean checkStudent (int num, DoubleLinkedList<Person> students){
  boolean found =false;
  int index=0;
  while (found==false && index<students.size()){
    if (num==students.get(index).studentNum){
      found=true;
    }
  }
  return found;
}

**Comment by ghost** [comment]
sorting is done

**Comment by Aaaaaaa3** [comment]
public Person checkStudent (int num, DoubleLinkedList students){
    boolean found =false;
    int index=0;
    while (found==false && index<students.size()){
      if (num==students.get(index).studentNum){
        return students.get(index);
      }
    }
    return null;
  }

**Comment by Aaaaaaa3** [comment]
public Person checkStudent (int num, DoubleLinkedList<Person> students){
    int index=0;
    while (index < students.size()){
      if (num==students.get(index).getNum()){
        return students.get(index);
      }
      index++;
    }
    return null;
  }
